#!/bin/bash

# '-e' Abort the script when an error occures.
# '-f' To ensure that globbing is globally disabled.
# '+x' To ensure debug mode is never enabled (prevents the password from leaking).
set -ef +x

# Detect the user.
# When the user is root exit out.
if [[ "$UID" == 0 ]]; then
   prinf "You must run this as a normal user"
   exit 1
fi

# Get the necessary configurations from the configuration file.
configLocation="$HOME/.config/bashpass"
config="$configLocation/bashpass.conf"
email="$(grep "email" "$config" | cut -d: -f2)"
passLocation="$HOME/$(grep "location" "$config" | cut -d: -f2)"
version="$(grep "version" "$config" | cut -d: -f2)"
timer="$(grep "timer" "$config" | cut -d: -f2)"

# Create the necessary directories/files if they doesn't exists
mkdir -p "${passLocation}" "${configLocation}"
touch "${config}"

function Help() {
   cat << EOF
BashPass version: $version
A simple password manager written in Bash.

bashpass [option] [name]                      - Basic command structure.

Options:
--help       or -h                            - Show this help message.
--version    or -v                            - Show the version number
--add        or -a                     [name] - Add a password.
--update     or -u                     [name] - Update a password.
--delete     or -d                     [name] - Delete a password.
--show       or -s                     [name] - Show a password.
--copy       or -c                     [name] - Copy a password to the clipboard.
--list       or -c                            - List all password.
EOF
}

function Version() {
   printf "BashPass version: %s" "${version}"
}

function RandomPassword() {
   printf "Do you want to generate a password [Y/n]: "
   read -r random

   case "${random}" in
      [Nn])
         printf "Enter a password: "
         read -rs password1
         printf "\n"

         printf "Enter the password again: "
         read -rs password2
         printf "\n"
         
         while [[ "${password1}" != "${password2}" ]]; do
            printf "Passwords ditn't match, please try again: "
            read -rs password2
            printf "\n"
         done

         password=${password1}
         ;;
      *)
         printf "Give the lenght of the password: "
         read -r lenght

         # Generate a password using '/dev/urandom'.
         # Call the 'tr' command to translate the password to a character set.
         password=$(</dev/urandom tr -dc '12345!@#$%qwertQWERTasdfgASDFGzxcvbZXCVB' | head -c "${lenght}"; echo "")
         ;;
   esac

   [[ -z "$password" ]] && Kill "Failed to set a password"

   # Write password to the 'password' file.
   printf "%s" "${password}" > "${passLocation}/${name}"
}

# Function to print out errors and exit afterwards.
function Kill() {
   printf "A error occured: %s" "${1}"
   printf "\n"
   Help
   printf "\n"
   exit 1
}

function PasswordExists() {
   while [[ -f ${passLocation}/${name}.gpg ]]; do
      printf "A password with the name %s already exists." "'${name}'"
      printf "\n"
      printf "Do you want to overwrite the existing password [y/N]: "
      read -r overwrite
      
      case "${overwrite}" in
         [Yy])
            rm -rf "${passLocation}/${name}.gpg"
            ;;
         *)
            printf "Enter a new name: "
            read -r name
            ;;
      esac
   done
}

function Add() {
   name="${1}"

   if [[ -z "${name}" ]]; then
      printf "Enter a name: "
      read -r name
   fi

   [[ -z "${name}" ]] && Kill "Failed to set a name"

   # Check if a password with the chosen name already exists.
   PasswordExists

   # Ask if the user want to generate a random password.
   RandomPassword

   # Encrypte the password file using gpg.
   gpg --encrypt --output "${passLocation}/${name}.gpg" --recipient "${email}" "${passLocation}/${name}"  &> /dev/null

   printf "Password %s has been successfully saved" "'${name}'"
   printf "\n"

   # Remove the Decrypted password file after reading
   # to prevent the password from being leaked afterwards.
   # ':?' to ensure this never expands to '/*'
   rm -rf "${passLocation:?}/${name}"
}

function Update() {
   name="${1}"

   if [[ -z "${name}" ]]; then
      printf "Enter the name of the password you want to update: "
      read -r name
   fi

   # Decrypte the password file.
   gpg --decrypt --output "${passLocation}/${name}" "${passLocation}/${name}.gpg" &> /dev/null

   # Ask if the user want to generate a random password.
   RandomPassword

   # Remove the ecrypted password file to prevent gpg from asking to overwrite.
   rm -rf "${passLocation:?}/${name}.gpg"

   # Encrypte the password file using gpg.
   gpg --encrypt --output "${passLocation}/${name}.gpg" --recipient "${email}" "${passLocation}/${name}"  &> /dev/null

   printf "Password %s has successfully been updated" "'${name}'"
   printf "\n"

   # Remove the Decrypted password file after reading
   # to prevent the password from being leaked afterwards.
   # ':?' to ensure this never expands to '/*'
   rm -rf "${passLocation:?}/${name}"
}

function Delete() {
   name="${1}"

   if [[ -z "${name}" ]]; then
      printf "Enter the name of the password you want to delete: "
      read -r name
   fi

   rm -rf "${passLocation}/${name}.gpg"
   printf "Password %s has successfully been deleted" "'${name}'"
   printf "\n"
}

function Show() {
   name="${1}"

   if [[ -z "${name}" ]]; then
      printf "Enter the name of the password you want to show: "
      read -r name
   fi

   # Decrypte the password file and show the password
   printf "Password: %s" "$(gpg -dq "${passLocation}/${name}.gpg")"
   printf "\n"
}

function Copy() {
   name="${1}"

   if [[ -z "${name}" ]]; then
      printf "Enter the name of the password you want to copy: "
      read -r name
   fi

   # Pipe the show function output to xclip to copy the password to the clipboard.
   Show "${name}" | xclip -selection clipboard

   # Wait for the timer to end clear the clipboard.
   # 'timer' can be changed in the config file.
   sleep "$timer" || kill 0
   xclip -selection clipboard < /dev/null
}

function List() {
   ls -1 "$passLocation"
   printf "\n"
}

# Detect 'gpg'
command -v gpg &> /dev/null || Kill "gpg is required"

# Ask the e-meil address to encrypt when it can't be found in the config file.
if [[ -z ${email} ]]; then
   printf "Enter the email address you created the gpg key with: "
   read -r email
   printf "email:%s" "${email}" >> "${config}"
fi

function Main() {
   case "$1" in
      "--help"| "-h") Help;;
      "--version"| "-v") Version;;
      "--add"| "-a") Add "${2}";;
      "--update"| "-u") Update "${2}";;
      "--delete"| "-d") Delete "${2}";;
      "--show"| "-s") Show "${2}";;
      "--copy"| "-c") Copy "${2}";;
      "--list"| "-l") List;;
      *) Kill "option '${1}' not found";;
   esac
}

# Check if an argument '$1' is given.
if [[ "$1" ]]; then
   Main "$@"
else
   Help
fi
