.TH "BASHPASS" "1" "2022-12-10" "BASHPASS 2022-12-23" "BASHPASS" "1"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq
.ad l
.nh
.SH "NAME"
bashpass \- command-line based password manager written in Bash.
.SH "SYNOPSIS"
bashpass [\fIOPTIONS\fR] [\fINAME\fR]
.RS 4
A \fINAME\fR does not need to be specified, the program will ask for it if none is given as an argument.
.RE
.SH "DESCRIPTION"
Together with \fBGnuPG\fR, this command-line based password manager allows the user to safely save passwords on his devices. All passwords are 100% stored locally and encrypted with the users own GPG key, so you don't have to trust a third party to store your passwords.
.RE
.SH "OPTIONS"
\fB-h\fR, \fB--help\fR
.RS 4
Display some helpful information.
.RE
.PP
\fB-v\fR, \fB--version\fR
.RS 4
Output the version.
.RE
.PP
\fB-l\fR, \fB--list\fR
.RS 4
Output a list of all the passwords (names).
.RE
.PP
\fB-a\fR, \fB--add\fR [\fINAME\fR]
.RS 4
Save a password, either auto generated or self chosen.
.RE
.PP
\fB-u\fR, \fB--update\fR [\fINAME\fR]
.RS 4
Change a saved password, either auto generated or self chosen.
.RE
.PP
\fB-d\fR, \fB--delete\fR [\fINAME\fR]
.RS 4
Delete a saved password from the system.
.RE
.PP
\fB-s\fR, \fB--show\fR [\fINAME\fR]
.RS 4
Output a password with a given name. This option will not clear the terminal so it is not recommended to use in crowded environments.
.RE
.PP
\fB-c\fR, \fB--copy\fR [\fINAME\fR]
.RS 4
Copy a password with a given name to the clipboard. After a certain amount of seconds the clipboard will be cleared to ensure security. The amount of seconds can be specified by changing the \fItimer\fR option in the configuration file (~/.config/bashpass/bashpass.conf). This is to insure security. This option requires either \fIxclip\fR(1) (X11), \fIxsel\fR(1) (X11) or \fIwl-clipboard\fR(1) (Wayland) to be installed on your system.
.RE
.PP
\fB-S\fR, \fB--sync\fR [\fIupload/download\fR]
.RS 4
Synchronize passwords between a git repository and your local device (in both directions). The repository can either be a self hosted or via a third-party such as GitHub or GitLab. This option requires \fIGIT\fR(1) to be installed on your system and a working internet connection to be available.
.PP
\fBNOTE\fR: you'll have to import your GPG key on every device you want to use the synchronization functionality. You can follow this guide <https://www.debuntu.org/how-to-importexport-gpg-key-pair/> for importing and exporting your GPG keys.
.RE
.SH "FILES AND DIRECTORIES"
~/.local/bin/bashpass
.RE
~/.config/bashpass/bashpass.conf
.RE
~/.local/share/bashpass/
.RE
.SH "SEE ALSO"
\fBbashpass.conf\fR(1)
.SH "AUTHOR"
\fBAnton Van Assche\fR <\fIhttps://www.github.com/AntonVanAssche\fR>
.SH "BUGS"
For bug reports and other issues regarding \fBBashPass\fR, including suggestions, please report to the GitHub link below, through which the project is developed.
.PP
.RS 2
\fIhttps://github.com/AntonVanAssche/BashPass\fR
.RE
