name: Test Makefile

on:
  push:
    paths:
      - "BSDmakefile"
      - "GNUmakefile"
  pull_request:
    paths:
      - "BSDmakefile"
      - "GNUmakefile"

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test installation
        run: |
          sudo make install

      - name: Test uninstall
        run: |
          sudo make install
          sudo make uninstall

  test-macos:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2

      - name: Test installation
        run: |
          make install

      - name: Test uninstall
        run: |
          make install
          make uninstall
