name: Build Packages

on:
  push:
    tags:
      - '*'

jobs:
  build-deb:
    runs-on: ubuntu-latest

    steps:
      - name: Set env
        run: |
          printf 'RELEASE_VERSION=%s' "${GITHUB_REF#refs/*/v}" >> ${GITHUB_ENV}

      - uses: actions/checkout@v3
        with:
          path: bashpass-${{ env.RELEASE_VERSION }}
          ref: refs/tags/v${{env.RELEASE_VERSION }}

      - name: Build DEB
        run: |
          /usr/bin/sed -i "s/RELEASE_VERSION/${{ env.RELEASE_VERSION }}/" bashpass-${{ env.RELEASE_VERSION }}/pkgs/deb/DEBIAN/control

          /usr/bin/mkdir -pv bashpass-${{ env.RELEASE_VERSION }}/pkgs/deb/usr/bin
          /usr/bin/mkdir -pv bashpass-${{ env.RELEASE_VERSION }}/pkgs/deb/usr/share/man/man1

          /usr/bin/cp -rv bashpass-${{ env.RELEASE_VERSION }}/bashpass bashpass-${{ env.RELEASE_VERSION }}/pkgs/deb/usr/bin/
          /usr/bin/cp -rv bashpass-${{ env.RELEASE_VERSION }}/docs/man/bashpass{,.conf}.1.gz bashpass-${{ env.RELEASE_VERSION }}/pkgs/deb/usr/share/man/man1/

          /usr/bin/dpkg-deb --build bashpass-${{ env.RELEASE_VERSION }}/pkgs/deb/ "bashpass_${{ env.RELEASE_VERSION }}_all.deb"

      - uses: actions/upload-artifact@v3
        with:
          name: deb
          path: bashpass_${{ env.RELEASE_VERSION }}_all.deb
