name: Shellcheck

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run shellcheck.
        run: |
          shopt -s nullglob
          shellcheck bashpass
          shellcheck scripts/* -e SC2016
