name: ShellCheck

on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: ShellCheck on bashpass.
        run: |
          while read -r; do
              shellcheck "${REPLY}"
          done < <(grep -rIzl '^#![[:blank:]]*/.*\(bash\|env[[:blank:]]\+bash\)' .)
