name: ShellCheck

on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: ShellCheck on bashpass.
        run: |
          shopt -s nullglob
          shellcheck bashpass

      - name: ShellCheck on scripts
        run: |
          shopt -s nullglob
          shellcheck scripts/*
